## Matrix inversion is usually a costly computation and their 
## may be some benefit to caching the inverse of a matrix rather
##than compute it repeatedly. This pair of functions are to
##cache the inverse of a matrix.

##assume that the matrix supplied is always invertible, hence 
##the checking for matrix is omitted. 
##This function is to create a list contains functions to set/get 
##the input matrix, and set/get the inverse of the input matrix
makeCacheMatrix <- function(x = matrix()) {
  invMatrix<-NULL
  set<-function(y){
    x<<-y
    invMatrix<<-NULL
  }
  get<-function() x
  setInv<-function(Invm) invMatrix<<- Invm
  getInv<-function() invMatrix
  
  list(set = set, get=get,
       setInv=setInv, 
       getInv=getInv)  
}


## function calculate the inverse of the special list generated by the 
## above function. However, it fist checks to see if the inverse has already
##been calculated. If so, it gets the inverse from the cache and skips the 
##computation. Otherwise, it calculates the inverse of the data and sets 
##the value of the inverse in the cache via the setInv function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m<-x$getInv()
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  data<-x$get()
  m<-solve(data, ...)
  x$setInv(m)
  m
}