## Matrix inversion is usually a costly computation and their 
## may be some benefit to caching the inverse of a matrix rather
##than compute it repeatedly. This pair of functions are to
##cache the inverse of a matrix.

##assume that the matrix supplied is always invertible, hence 
##the checking for matrix is omitted. 
##This function is to create a list contains functions to set/get 
##the input matrix, and set/get the inverse of the input matrix

makeCacheMatrix <- function(x = matrix()) {
  #init. reset to NULL
  invMatrix<-NULL
  
  #setter and getter for matrix X
  set<-function(y){
    x<<-y
    invMatrix<<-NULL
  }
  get<-function(){
    x 
  }
  
  #setter and getter for the inversed matrix
  setInv<-function(Invm){
    invMatrix<<- Invm
  } 
  getInv<-function(){
    invMatrix
  } 
  
  #This is a list of the internal functions 
  #so a calling function knows how to access those methods.       
  list(set = set, get=get,
       setInv=setInv, 
       getInv=getInv)  
}


## function calculate the inverse of the special list generated by the 
## above function. However, it fist checks to see if the inverse has already
##been calculated. If so, it gets the inverse from the cache and skips the 
##computation. Otherwise, it calculates the inverse of the data and sets 
##the value of the inverse in the cache via the setInv function

cacheSolve <- function(x, ...) {
  #access the object x and get the Inverse matrix      
  m<-x$getInv()
  
  #if it was already cached, return the matrix 
  # and end execution here
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  
  #if m is NULL, calaculte inverse using solve function of R
  # and then store the inverse into x object
  data<-x$get()
  m<-solve(data, ...)
  x$setInv(m)
  
  #return the inverse
  m
}